{% set name = "nsls2-detector-handlers" %}
{% set version = "0.1.0" %}
{% set sha256 = "433d4dda1feed294faff39b855a3106bb2bab5d47d83a61a766d6e5158cd1804" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - h5py
    - numpy
    - pandas

test:
  requires:
    - python {{ python_min }}
  imports:
    - nsls2_detector_handlers

about:
  home: https://github.com/bluesky/nsls2-detector-handlers
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Detector handlers specific to NSLS-II

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
